[project]
name = "mlfiresafetytutor"
version = "0.1.0"
requires-python = ">=3.11"
description = "ML FireSafetyTutor - Interactive platform for learning ML in fire safety applications"
readme = "readme.txt"
dependencies = [
    "streamlit>=1.45.0",
    "pandas>=2.2.3",
    "numpy>=2.2.5",
    "matplotlib>=3.10.1",
    "plotly>=6.0.1",
    "scikit-learn>=1.6.1",
    "sqlalchemy>=2.0.40",
    "psycopg2-binary>=2.9.10",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "anthropic>=0.50.0",
    "openai>=1.77.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"