[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5
maxMessageSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF5722"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"