# Файл для конфигурации секретов, которые будут доступны в приложении
# Не включайте реальные секреты в этот файл, они должны быть добавлены 
# через интерфейс Streamlit Share

# Пример: коннект к базе данных
[postgres]
host = "dummy_host"
port = 5432
dbname = "dummy_db"
user = "dummy_user"
password = "dummy_password"